print("-"*60)
print("Seja bem vindo a cauculadora de médias da escola dos sonhos!")
print("Vamos começar a caucular!")
print("-"*60)
print("-"*30)
port =  float(input("Português: "))
print("-"*30)
mat = float(input("Matemática: "))
print("-"*30)
economia = float(input("Economia: "))
print("-"*30)
educfinan = float(input("Educação financeira: "))
print("-"*30)
geografia = float(input("Geografia: "))
print("-"*30)
historia = float(input("História: "))
print("-"*30)
ing = float(input("Inglês: "))
print("-"*30)
projvida = float(input("Projeto de Vida: "))
print("-"*30)
atvfsc = float(input("Atividade fisica: "))
print("-"*30)
empreen = float(input("Empreendedorismo: "))
print("-"*60)

soma = port + mat + economia + educfinan + geografia + historia + ing + projvida + atvfsc + empreen
media = soma / 10
print("Sua média geral é de {}".format(media))
